name: Linux CI
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CXX: ${{ matrix.compiler }}
      INSPIRCD_DEBUG: 3
      INSPIRCD_VERBOSE: 1
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update --assume-yes
          sudo apt-get install --assume-yes --no-install-recommends \
            clang \
            g++ \
            git \
            libargon2-dev \
            libc++-dev \
            libc++abi-dev \
            libgnutls28-dev \
            libldap2-dev \
            libmaxminddb-dev \
            libmbedtls-dev \
            libmysqlclient-dev \
            libpcre2-dev \
            libpcre3-dev \
            libpq-dev \
            libre2-dev \
            libsqlite3-dev \
            libssl-dev \
            make \
            pkg-config

      - name: Work around a bug in GitHub Actions
        if: matrix.compiler == 'clang++'
        run: |
          sudo apt-get remove gcc-11 libgcc-11-dev

      - name: Run configure
        run: |
          ./configure --enable-extras "argon2 geo_maxmind ldap mysql pgsql regex_pcre regex_pcre2 regex_posix regex_re2 sqlite3 ssl_gnutls ssl_mbedtls ssl_openssl sslrehashsignal"
          ./configure --development --disable-auto-extras --socketengine ${{ matrix.socketengine }}

      - name: Build core
        run: |
          INSPIRCD_TARGET=inspircd make --jobs $(($(getconf _NPROCESSORS_ONLN) + 1))

      - name: Build modules
        run: |
          INSPIRCD_TARGET=modules make --jobs $(($(getconf _NPROCESSORS_ONLN) + 1))

      - name: Install
        run: |
          make install

      - name: Run
        run: |
          touch ${{ github.workspace }}/run/conf/inspircd.conf
          ${{ github.workspace }}/run/inspircd start
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang++
          - g++
        socketengine:
          - epoll
          - poll
          - select
